#! /usr/bin/bash

RED='\[\033[0;31m\]'
GREEN='\[\033[0;32m\]'
YELLOW='\[\033[0;33m\]'
BLUE='\[\033[0;34m\]'
MAGENTA='\[\033[0;35m\]'
CYAN='\[\033[0;36m\]'
RESET='\[\033[0m\]'

# Функція для виводу гілки Git
parse_git_branch() {
  git branch --show-current 2>/dev/null
}

# Промпт
PS1="${BLUE}\u${RESET}@${MAGENTA}\h${RESET}:${CYAN}\w${RESET}\$(
  branch=$(parse_git_branch)
  if [ -n \"$branch\" ]; then
    echo \" ${YELLOW} $branch${RESET}\"
  fi
)\n\$ "
